django/week02/myinsta/urls.py
from django.contrib import admin
from django.urls import path, include
from posts.views import url_view, url_parameter_view, function_view, class_view
from posts.views import index #방금 만든 인덱스 임포트해서 넣어주고 #posts>urls.py의 url을 posts/뒤에 붙이도록 만듦

urlpatterns = [
    path('admin/', admin.site.urls),
    path('url/', url_view),
    path('url/<str:username>/', url_parameter_view),
    path('fbv/', function_view),
    path('cbv/', class_view.as_view()),

    path('', index, name='index'),
    path('posts/', include('posts.urls', namespace='posts')),
]

django/week02/posts/urls.py
from django.urls import path

from .views import post_create_view, post_delete_view
from .views import post_list_view, post_update_view, post_detail_view

app_name='posts'

urlpatterns = [
    path('', post_list_view, name='post-list'),
    path('new/', post_create_view),
    path('<int:id>/', post_detail_view),
    path('<int:id>/edit', post_update_view),
    path('<int:id>/delete', post_delete_view),
]

django/week02/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
# Create your models here.

User=get_user_model()

class Post (models.Model):
    image=models.ImageField(verbose_name='이미지', null=True, blank=True)
    content=models.TextField(verbose_name='내용')
    created_at = models.DateTimeField(verbose_name='작성일', auto_now_add=True)
    view_count=models.IntegerField(verbose_name='조회수', default=0)
    writer=models.ForeignKey(to=User, on_delete=models.CASCADE, verbose_name='작성자', null=True, blank=True)

class Comment(models.Model):
    content=models.TextField(verbose_name='내용')
    created_at=models.DateTimeField(verbose_name='작성일',auto_now_add=True)
    post=models.ForeignKey(to='Post', on_delete=models.CASCADE, verbose_name='게시글')
    writer=models.ForeignKey(to=User, on_delete=models.CASCADE, verbose_name='작성자', null=True)

django/week02/posts/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse

from django.views.generic import ListView
from .models import Post

# Create your views here.
#def url_view(request):
#    return HttpResponse('url.view')

def index(request):
    return render(request, 'index.html')

def post_list_view(request):
    return render(request, 'posts/post_list.html')

def post_detail_view(request, id):
    return render(request, 'posts/post_detail.html')

def post_create_view(request):
    return render(request, 'posts/post_form.html')

def post_update_view(request, id):
    return render(request, 'posts/post_update.html')

def post_delete_view(request, id):
    return render(request, 'posts/post_confirm_delete.html')

class class_view(ListView):
    model = Post
    template_name='cbv_view.html'


def url_view(request):
    data = {'code':'001','msg':'OK'}
    return HttpResponse('<h1>url_views</h1>')

def url_parameter_view(request, username):
    print('url_parameter_view()')
    print(f'username: {username}')
    print(f'request.GET: {request.GET}')
    return HttpResponse(username)

def function_view(request):
    print(f'request.method:{request.method}')
    if request.method == "GET":
        print(f'request.GET: {request.GET}')
    elif request.method == "POST":
        print(f'request.POST: {request.POST}')
    return render(request, 'view.html')

django/week02/myinsta/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block  title  %}{% endblock %} Page | 멋스타그램</title>
</head>
<body>
    <div>
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

django/week02/myinsta/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Index Page | 멋스타그램 </title>
</head>
<body>
    <h1>index 화면</h1>
    <u1>
        <li><a href="{% url 'posts:post-list' %}">게시글 목록</a></li>
    </ul>
</body>
</html>

django/week02/myinsta/templates/posts/post_confirm_delete.html
{% extends 'base.html' %}
{% block title %}Delete{% endblock %}

{% block content %}
<h1>Post 삭제 화면</h1>
{% endblock %}

django/week02/myinsta/templates/posts/post_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>POST 상세 화면</h1> 
</body>
</html>

django/week02/myinsta/templates/posts/post_form.html
{% extends 'base.html' %}
{% block title %}Form{% endblock %}

{% block content %}
<h1>Post 입력 화면</h1>
{% endblock %}

django/week02/myinsta/templates/posts/post_list.html
{% extends 'base.html' %}
{% block title %}List{% endblock %}

{% block content %}
<h1>Post 목록 화면</h1>
{% endblock %}

django/week02/myinsta/templates/posts/post_update.html
{% extends 'base.html' %}
{% block title %}Update{% endblock %}

{% block content %}
<h1>Post 수정 화면</h1>
{% endblock %}

django/week02/posts/templates/cbv_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for object in object_list %}
        {{ object }}
    {% endfor %}
</body>
</html>

django/week02/posts/templates/view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a href="/fbv/">새로고침</a>
    <form action="" method="get">
        <input type="text" name="var">
        <input type="submit" value="GET 제출">
    </form>
    <form action="" method="post">
        <input type="text" name="var"> {% csrf_token %}
        <input type="submit" value="POST 제출">
</body>
</html>